In [2]:
# Import the needed libraries
import numpy as np

**72. How to swap two rows of an array?** 

In [6]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
arr[[0,2]] = arr[[2,0]]
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]


**75. How to compute averages using a sliding window over an array?**

In [11]:
def moving_average(arr, n=3) :
    rearange = np.cumsum(arr)
    rearange[n:] = rearange[n:] - rearange[:-n]
    return rearange[n - 1:] / n

arr = np.arange(20)

print(moving_average(arr,3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]
