In [2]:
# Import the needed libraries
import numpy as np


**13. Create a 10x10 array with random values and find the minimum and maximum values**

In [10]:
arr = np.random.normal(size=(10,10))
print(arr)
print(np.max(arr))
print(np.min(arr))

[[ 0.24581181 -0.43332449  1.41422925  2.37287949 -1.02633006 -2.88893475
   0.18798076  1.87175179 -2.80048276  0.55584108]
 [ 1.40879539 -0.92329901 -1.87019809  0.81613913 -0.80930377  0.53002992
  -0.17654284  0.54487084 -1.76960363 -1.67791971]
 [ 0.89579071 -0.45331426 -1.16774056  1.69004806 -1.56423564  0.86137552
  -0.24754901 -2.87225396  0.19539363  0.60047591]
 [ 0.60550839  0.07572819 -0.03786918 -1.02740491 -0.73444464  1.07290501
   0.44236115 -0.19125165  0.92990991  0.70852448]
 [-1.8246566  -0.08864829  0.33857783 -0.25868669 -0.06776519  0.12213236
  -0.11199042  0.70255683 -0.61210733 -1.17794457]
 [-0.32234958 -0.59086864 -1.16284281 -0.46557766 -0.51345648  0.02429902
   0.7184361  -0.70186325  0.63359625  0.01834795]
 [ 2.08331144  0.84400801 -0.43692407  0.55292606  0.88152178 -0.58999075
   0.12634832 -0.63390238  0.10832252 -2.04037787]
 [ 0.04560745  0.49969281  0.82794738  0.11008824 -0.86901139 -0.15750843
  -0.22094657  0.83303279  0.60411944  0.77201743]


**15. Create a 2d array with 1 on the border and 0 inside**

In [13]:
arr = np.array([[0,0,0],[0,1,0],[0,0,0]])
print(arr)
arr.shape

[[0 0 0]
 [0 1 0]
 [0 0 0]]


(3, 3)