In [2]:
# Import the needed libraries
import numpy as np

**72. How to swap two rows of an array?** 

In [6]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
arr[[0,2]] = arr[[2,0]]
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]


**75. How to compute averages using a sliding window over an array?**

In [18]:
array = np.random.randint(2,6, size=(3,3))
print (array)
a = np.cumsum(array)
print("\n")
print (a)
print ("Average:", round(np.average(a),2))

[[4 3 5]
 [2 4 2]
 [5 5 4]]


[ 4  7 12 14 18 20 25 30 34]
Average: 18.22
