In [7]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import GridSearchCV

In [2]:
data = load_iris()

In [3]:
X = data.data
y = data.target

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state = 42)

In [8]:
model = RandomForestClassifier()

In [9]:
model.fit(X_train,y_train)

RandomForestClassifier()

In [10]:
y_pred = model.predict(X_test)

In [11]:
print(cross_val_score(model, X_train, y_train, cv=3))

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[0.975 0.925 0.975]
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



# Zoo Data

In [12]:
zoo_data = pd.read_csv('zoo.data', header = None)

In [23]:
X = zoo_data.iloc[:,1:17]
y = zoo_data[17]

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state = 42)

In [25]:
model = RandomForestClassifier(n_estimators=10)

In [26]:
model.fit(X_train,y_train)

RandomForestClassifier(n_estimators=10)

In [27]:
y_pred = model.predict(X_test)

In [28]:
print(cross_val_score(model, X_train, y_train, cv=3))

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[0.96296296 1.         0.96153846]
[[12  0  0  0  0  0]
 [ 0  2  0  0  0  0]
 [ 1  0  0  0  0  0]
 [ 0  0  0  2  0  0]
 [ 0  0  0  0  3  0]
 [ 0  0  0  0  0  1]]
              precision    recall  f1-score   support

           1       0.92      1.00      0.96        12
           2       1.00      1.00      1.00         2
           3       0.00      0.00      0.00         1
           4       1.00      1.00      1.00         2
           6       1.00      1.00      1.00         3
           7       1.00      1.00      1.00         1

    accuracy                           0.95        21
   macro avg       0.82      0.83      0.83        21
weighted avg       0.91      0.95      0.93        21



/opt/anaconda3/envs/ml/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/anaconda3/envs/ml/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/anaconda3/envs/ml/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
